[project]
name = "lizozom"
version = "0.1.0"
description = ""
authors = [
    {name = "Liza Katz",email = "lizka.k@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
